---
title: Coded Glass
timezone: UTC
collections:
  interviews:
    title: Interviews
    output: true
  journal:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: ''
    image: ''
    description: ''
    keywords: ''
- scope:
    path: ''
    type: journal
  values:
    layout: post
    permalink: "/journal/:title/"
    author: ''
    tweet: ''
    image: ''
    description: ''
    keywords: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: ''
    description: ''
    keywords: ''
    canonical: ''
url: https://example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: 
email: your-email@example.com
facebook_username: jekyllrb
twitter_username: jekyllrb
instagram_username: jekyllrb
google_tag_manager_id: 
test_google_tag_manager_id: 
cloudinary_cloud_name: 
cloudinary_fetch_skip_transform:
- ".svg"
permalink: pretty
plugins:
- jekyll-cloudinary_fetcher
- jekyll-sitemap
keep_files:
- assets
exclude:
- ".github"
- ".gitignore"
- Gemfile.lock
- node_modules
- reports
- source
- test
- README.md
- package.json
- ".babelrc"
- ".browserslistrc"
- ".editorconfig"
- ".eslintignore"
- ".eslintrc"
- ".eslintrc.json.sample"
- postcss.config.js
- ".stylelintignore"
- ".stylelintrc"
- webpack.config.js
- yarn.lock
- yarn-error.log
