---
title: Coded Glass
timezone: UTC
collections:
  interviews:
    title: Interviews
    output: true
  shards:
    title: Shards
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    author: ''
    image: ''
    description: ''
    keywords: ''
- scope:
    path: ''
    type: shards
  values:
    layout: post
    permalink: "/shards/:title/"
    author: ''
    tweet: ''
    image: ''
    description: ''
    keywords: ''
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: ''
    description: ''
    keywords: ''
    canonical: ''
url: https://example.com
description: 'Coded Glass is a new media project that blends art, tweets from the
  Metoo movement, and morse code.

'
keywords: 'art, metoo tweets, morse code, '
email: your-email@example.com
facebook_username: 
twitter_username: 
instagram_username: 
google_tag_manager_id: 
test_google_tag_manager_id: 
cloudinary_cloud_name: 
cloudinary_fetch_skip_transform:
- ".svg"
permalink: pretty
plugins:
- jekyll-cloudinary_fetcher
- jekyll-sitemap
keep_files:
- assets
exclude:
- ".github"
- ".gitignore"
- Gemfile.lock
- node_modules
- reports
- source
- test
- README.md
- package.json
- ".babelrc"
- ".browserslistrc"
- ".editorconfig"
- ".eslintignore"
- ".eslintrc"
- ".eslintrc.json.sample"
- postcss.config.js
- ".stylelintignore"
- ".stylelintrc"
- webpack.config.js
- yarn.lock
- yarn-error.log
